[package]
name = "xswezan/conditionenvironment"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Janitor = "howmanysmall/janitor@1.15.1"
Promise = "lukadev-0/typed-promise@4.0.2"